# -*- coding: utf-8 -*-
"""PDFium is used by one scan at a time, and nothing of it outlives the read.

    pytest tests/test_pdfium_one_at_a_time.py -v

fill_burp_pdf_exchanges reads a printed Burp report's request / response boxes
with pypdfium2. PDFium is not thread-safe: a VAPT scan of a Burp PDF on a
developer PC stopped the whole server inside pdfium.dll (Windows exception
0x80000003), and four overlapping calls on the real report did the same in 3
runs of 3. Its pages were also never closed, so the garbage collector freed
them later on whichever thread it ran. Now one lock covers the read and every
page, text page and document is closed inside it -- the same calls survived 5
runs of 5 and 8 x 10 overlapping, with the same text out.

Here a stand-in pypdfium2 fails the test if two reads overlap or anything is
left open.
"""
import sys
import threading
import time
import types

from src.core.parsers import doc_parsers

TEXT = ("Burp Suite Professional\n"
        "1. SQL injection\n"
        "Issue detail\nThe id parameter appears to be vulnerable.\n"
        "Request 1\n"
        "Response 1\n"
        "Report generated by Burp Suite")
BOX = "GET /catalog?id=1' HTTP/2"


class _Stats:
    def __init__(self):
        self.lock = threading.Lock()
        self.active = 0
        self.max_active = 0
        self.opened = {"doc": 0, "page": 0, "tp": 0}
        self.closed = {"doc": 0, "page": 0, "tp": 0}

    def open(self, kind):
        with self.lock:
            self.opened[kind] += 1

    def close(self, kind):
        with self.lock:
            self.closed[kind] += 1


def _fake_pdfium(stats):
    class TextPage:
        def __init__(self):
            stats.open("tp")

        def get_text_range(self):
            time.sleep(0.01)                 # widen the window two reads could share
            return TEXT

        def get_charbox(self, i):
            return (0.0, 100.0, 500.0, 110.0)

        def get_text_bounded(self, left, bottom, right, top):
            return BOX

        def close(self):
            stats.close("tp")

    class Page:
        def __init__(self):
            stats.open("page")

        def get_textpage(self):
            return TextPage()

        def get_size(self):
            return (600.0, 800.0)

        def close(self):
            stats.close("page")

    class PdfDocument:
        def __init__(self, data):
            stats.open("doc")
            with stats.lock:
                stats.active += 1
                stats.max_active = max(stats.max_active, stats.active)

        def __len__(self):
            return 2

        def __getitem__(self, i):
            return Page()

        def close(self):
            with stats.lock:
                stats.active -= 1
            stats.close("doc")

    return types.SimpleNamespace(PdfDocument=PdfDocument)


def test_the_boxes_are_still_put_back(monkeypatch):
    stats = _Stats()
    monkeypatch.setitem(sys.modules, "pypdfium2", _fake_pdfium(stats))
    out = doc_parsers.fill_burp_pdf_exchanges(TEXT, b"%PDF")
    assert "Request 1\n" + BOX in out


def test_reads_never_overlap_and_nothing_is_left_open(monkeypatch):
    stats = _Stats()
    monkeypatch.setitem(sys.modules, "pypdfium2", _fake_pdfium(stats))
    results = []

    def scan():
        for _ in range(5):
            results.append(doc_parsers.fill_burp_pdf_exchanges(TEXT, b"%PDF"))

    threads = [threading.Thread(target=scan) for _ in range(6)]
    for t in threads:
        t.start()
    for t in threads:
        t.join()

    assert len(results) == 30 and all(BOX in r for r in results)
    assert stats.max_active == 1, "two scans used PDFium at the same time"
    assert stats.opened == stats.closed, (stats.opened, stats.closed)


def test_a_failed_read_still_closes_everything(monkeypatch):
    stats = _Stats()
    fake = _fake_pdfium(stats)

    def broken(self, i):
        raise RuntimeError("damaged page")

    monkeypatch.setattr(fake.PdfDocument, "__getitem__", broken)
    monkeypatch.setitem(sys.modules, "pypdfium2", fake)
    assert doc_parsers.fill_burp_pdf_exchanges(TEXT, b"%PDF") == TEXT   # unchanged, as before
    assert stats.closed["doc"] == stats.opened["doc"] == 1
    assert not doc_parsers._PDFIUM_LOCK.locked()
