# -*- coding: utf-8 -*-
"""What a report states is what the tool saves.

Found by reading every real VAPT document on the development machine
independently of the parsers and comparing, field by field, with what the
worker stored:

  * Nessus "by host" HTML: one plugin on two ports of a host had one identity,
    and the worker kept one -- 10 of 347 findings lost; "Patch Report" was given
    the CVEs its output mentions (and a KEV badge); <br> was dropped, so
    sentences ran together in 21 descriptions and solutions.
  * Nessus "by plugin" HTML: the port in "203.0.113.52 (tcp/445/cifs)" was lost.
  * Burp HTML: requests came out as one line ("HTTP/2Host: ..."), list items
    and paragraphs ran together, and Collaborator interactions -- the proof of
    an out-of-band finding -- were not read.
  * Burp PDF: the Collaborator interaction was dropped; "AngularJS v1.7.7. This"
    ended a description at "v1.7.".
  * Burp text printed in part: an unnumbered instance line became the title;
    the next finding took the first one's host.
  * Pentest-report tables with no remediation column: a "Fix Release" or remark
    cell was published as the remediation ('patch fix (April)"').
  * Pentest-report target cells: the field named beside the URL ("Phone
    Number") was dropped.
"""
import pytest

from src.core.parsers.burp_parser import BurpParser
from src.core.parsers.nessus_parser import NessusParser
from src.core.parsers.pentest_report_parser import _hosts


# -- Nessus HTML ---------------------------------------------------------------

_N = [0]


def _plugin(pid, title, output, refs="", desc="Line one.<br>Line two."):
    """One plugin block, laid out as a real "by host" export is (one element per line)."""
    _N[0] += 1
    bid = f"id{_N[0]}"
    ref = (f'<div class="details-header">References<div class="clear"></div></div>\n'
           f'<div>{refs}<div class="clear"></div></div>\n') if refs else ""
    return f"""
<div id="{bid}" class="" onclick="toggleSection('{bid}-container');">{pid} - {title}<div id="{bid}-toggletext"> - </div></div>
<div id="{bid}-container" class="section-wrapper">
<div class="details-header">Synopsis<div class="clear"></div></div>
<div>Synopsis.<div class="clear"></div></div>
<div class="details-header">Description<div class="clear"></div></div>
<div>{desc}<div class="clear"></div></div>
<div class="details-header">Solution<div class="clear"></div></div>
<div>Fix it.<div class="clear"></div></div>
<div class="details-header">Risk Factor<div class="clear"></div></div>
<div>None<div class="clear"></div></div>
{ref}<div class="details-header">Plugin Information<div class="clear"></div></div>
<div>Published: 2010/05/11<div class="clear"></div></div>
<div class="details-header">Plugin Output<div class="clear"></div></div>
{output}
</div>
"""


def _by_host(*plugins):
    return ("""<html><body><h1>Report generated by Tenable Nessus</h1>
<div class="details-header">Host Information<div class="clear"></div></div>
<div class="table-wrapper details"><table><tbody>
<tr><td>IP:</td><td>10.0.0.5</td></tr>
</tbody></table></div>
<div class="details-header">Vulnerabilities<div class="clear"></div></div>
""" + "".join(plugins) + "</body></html>")


def test_one_plugin_on_two_ports_is_two_findings():
    html = _by_host(_plugin("11011", "Microsoft Windows SMB Service Detection",
                            "<h2>tcp/139/smb</h2>\n<div>An SMB server is running on this port.<div class=\"clear\"></div></div>"),
                    _plugin("11011", "Microsoft Windows SMB Service Detection",
                            "<h2>tcp/445/cifs</h2>\n<div>A CIFS server is running on this port.<div class=\"clear\"></div></div>"))
    a, i = NessusParser().parse("by_host.html", html)
    fs = a + i
    assert sorted(f.target for f in fs) == ["10.0.0.5:139/tcp (smb)", "10.0.0.5:445/tcp (cifs)"]
    assert len({f.dedup_key() for f in fs}) == 2


def test_a_host_level_plugin_keeps_the_host():
    a, i = NessusParser().parse("by_host.html", _by_host(_plugin(
        "19506", "Nessus Scan Information", "<h2>tcp/0</h2>\n<div>Scan information.<div class=\"clear\"></div></div>")))
    assert [f.target for f in a + i] == ["10.0.0.5"]


def test_the_patch_report_is_not_given_the_cves_its_output_names():
    html = _by_host(_plugin("66334", "Patch Report",
                            "<h2>tcp/0</h2>\n<div>+ Install WinRAR 7.13 (CVE-2025-8088)<div class=\"clear\"></div></div>"),
                    _plugin("248462", "RARLAB WinRAR &lt; 7.13 Directory Traversal",
                            "<h2>tcp/445/cifs</h2>\n<div>Installed version : 7.1.0.0<div class=\"clear\"></div></div>",
                            refs="CVE<br>CVE-2025-8088<br>XREF<br>IAVA:2025-A-0608"))
    a, i = NessusParser().parse("by_host.html", html)
    got = {f.title: f.cve_list for f in a + i}
    assert got["Patch Report"] == []
    assert got["RARLAB WinRAR < 7.13 Directory Traversal"] == ["CVE-2025-8088"]


def test_a_line_break_in_the_description_is_kept():
    a, i = NessusParser().parse("by_host.html", _by_host(_plugin(
        "65057", "Insecure Windows Service Permissions",
        "<h2>tcp/445/cifs</h2>\n<div>Path : C:\\svc.exe<div class=\"clear\"></div></div>",
        desc="vulnerable to privilege escalation attacks.<br>An unprivileged user could modify it.")))
    assert "attacks.An" not in (a + i)[0].description
    assert " ".join((a + i)[0].description.split()) == \
        "vulnerable to privilege escalation attacks. An unprivileged user could modify it."


# -- Burp HTML -----------------------------------------------------------------

BURP_HTML = """<html><body>
<span class="BODH0" id="1">1.&nbsp;External service interaction (HTTP)</span>
<h2>Summary</h2><table class="summary_table"><tbody>
<tr><td>Severity:&nbsp;&nbsp;</td><td><b>High</b></td></tr>
<tr><td>Confidence:&nbsp;&nbsp;</td><td><b>Certain</b></td></tr>
<tr><td>Host:&nbsp;&nbsp;</td><td><b>https://shop.test</b></td></tr>
<tr><td>Path:&nbsp;&nbsp;</td><td><b>/catalog</b></td></tr></tbody></table>
<h2>Issue detail</h2><span class="TEXT">It is possible to induce requests.<br><br>The cookie:<ul><li>AWSALB</li></ul>The cookie is not a session token.</span>
<h2>Request 1</h2><div class="rr_div"><span>GET /catalog HTTP/2<br>Host: shop.test<br>Accept: */*</span></div>
<h2>Collaborator HTTP interaction</h2><span class="TEXT">The Collaborator server received an HTTP request.</span>
<h4>Request to Collaborator</h4><div class="rr_div"><span>GET / HTTP/1.1<br>Host: abc.oastify.com</span></div>
<div class="rule"></div>
</body></html>"""


def _burp_html():
    a, i = BurpParser()._parse_html(BURP_HTML)
    return (a + i)[0]


def test_a_request_keeps_its_lines():
    assert "GET /catalog HTTP/2\nHost: shop.test\nAccept: */*" in _burp_html().evidence


def test_list_items_and_paragraphs_do_not_run_together():
    d = _burp_html().description
    assert "AWSALBThe" not in d and "requests.The" not in d


def test_the_collaborator_interaction_is_part_of_the_proof():
    ev = _burp_html().evidence
    assert "[Collaborator HTTP interaction]" in ev
    assert "Request to Collaborator" in ev and "GET / HTTP/1.1\nHost: abc.oastify.com" in ev


# -- Burp PDF text -------------------------------------------------------------

BURP_PDF = """1. External service interaction (HTTP)
Next
Summary
Severity: High
Confidence: Certain
Host: https://shop.test
Path: /catalog
Issue detail
It is possible to induce the application to perform server-side HTTP requests.
Request 1
GET /catalog HTTP/2
Host: shop.test
Response 1
HTTP/2 200 OK
Content-Length: 3
Collaborator HTTP interaction
The Collaborator server received an HTTP request.
Request to Collaborator
GET / HTTP/1.1
2. Client-side template injection
Previous
Summary
Severity: High
Confidence: Firm
Host: https://shop.test
Path: /search
Issue detail
The HTML page uses AngularJS v1.7.7. This proof-of-concept attack demonstrates an injection.
"""


def _burp_pdf():
    a, i = BurpParser()._parse_plaintext(BURP_PDF)
    return {f.title.split(" (")[0]: f for f in a + i}


def test_the_pdf_collaborator_interaction_is_its_own_part():
    ev = _burp_pdf()["External service interaction"].evidence
    assert "[HTTP Response 1]\nHTTP/2 200 OK\nContent-Length: 3" in ev
    assert "[Collaborator HTTP interaction]\nThe Collaborator server received an HTTP request." in ev


def test_a_version_number_does_not_end_the_description():
    assert "This proof-of-concept attack demonstrates" in _burp_pdf()["Client-side template injection"].description


PARTIAL = """Burp Scanner Sample Report
6. External service interaction (HTTP)
https://shop.test/catalog/product/stock [Referer HTTP header]
Severity: High
Confidence: Firm
Host: https://shop.test
Path: /catalog/product/stock
Issue detail
It is possible to induce requests.
7. Vulnerable JavaScript dependency
Severity: Medium
Issue detail
The application uses a JavaScript library with known vulnerabilities.
"""


def test_an_unnumbered_instance_line_is_not_the_title():
    a, i = BurpParser()._parse_plaintext(PARTIAL)
    titles = sorted(f.title for f in a + i)
    assert titles[0].startswith("External service interaction (HTTP) (https://shop.test/catalog/product/stock")


def test_a_finding_naming_no_host_does_not_take_the_previous_ones():
    a, i = BurpParser()._parse_plaintext(PARTIAL)
    dep = next(f for f in a + i if f.title.startswith("Vulnerable JavaScript dependency"))
    assert dep.target == "Not recorded"


# -- pentest-report tables ------------------------------------------------------

def test_a_table_without_a_remediation_column_gives_no_remediation():
    from src.core.parsers.pentest_report_parser import PentestReportParser
    text = ("Vulnerability Assessment Report\n"
            "CVE Number | Vuln Description | RHEL severity | Fix Release\n"
            "CVE-2021-22543 | RHEL 7 : kernel (RHSA-2021:3801) | Important | \"Quarterly patch fix (April)\"\n"
            "CVE-2016-4658 | RHEL 7 : libxml2 (RHSA-2021:3810) | Important | \"Quarterly patch fix (April)\"\n")
    a, i = PentestReportParser().parse("report.docx", text)
    assert a and all(f.remediation == "" for f in a + i), [f.remediation for f in a + i]


@pytest.mark.parametrize("cell,target", [
    ("https://192.0.2.47:9007 Phone Number", "https://192.0.2.47:9007 [Phone Number]"),
    ("https://192.0.2.47:9007", "https://192.0.2.47:9007"),
    ("Scoped Host Targets, 198.51.100.93, 203.0.113.52", "Scoped Host Targets, 198.51.100.93, 203.0.113.52"),
    ("198.51.100.93, 203.0.113.52", "198.51.100.93, 203.0.113.52"),
    ("Backend F5", "Backend F5"),
])
def test_a_target_cell_keeps_what_it_names(cell, target):
    assert _hosts(cell) == target


def test_the_report_and_card_split_a_collaborator_part():
    from src.core.report_exporter import _poc_sections
    parts = _poc_sections("[HTTP Response 1]\nHTTP/2 200 OK\n\n[Collaborator DNS interaction]\nA DNS lookup.")
    assert [p[0] for p in parts] == ["HTTP Response 1", "Collaborator DNS interaction"]
