# -*- coding: utf-8 -*-
"""A VAPT finding's proof of concept is kept whole, in labelled parts.

It was cut at every step: the Burp parser kept 500 characters of an issue
detail (a card ended "You shoul"), 700 of each request and response and only
the first two exchanges; the HTML and XML paths 400 and 1200; Nessus, Qualys,
sqlmap and the code scanners 500 to 1500; the worker cut again at 1200 and the
reports at 2500. Now the proof is whole, each request / response / issue detail
under its own label on the card and in both reports. Only a raw HTTP body past
20,000 characters is cut, at a line, saying how much is left out.

The page's own functions are run under Node where it is available.
"""
import base64
import io
from html import escape
import json
import os
import re
import shutil
import subprocess

import pytest
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

import src.core.bg_worker as worker
from src.core.parsers import parse_tool_file
from src.core.parsers.burp_parser import BurpParser
from src.core.parsers.finding_schema import POC_MAX_CHARS, full_poc
from src.db.database import AuditReport, Base, Finding

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
APP_JS = os.path.join(ROOT, "src", "api", "static", "app.js")

DETAIL = ("The value of the term request parameter is copied into the value of an HTML tag attribute which is "
          "encapsulated in double quotation marks. The payload \">\n<NVWrC> was submitted in the term parameter. "
          "This input was echoed unmodified in the application's response.\n \nThis behavior demonstrates that it "
          "is possible to inject new HTML tags into the returned document. An attempt was made to identify a full "
          "proof-of-concept attack\nfor injecting arbitrary JavaScript but this was not successful. You should "
          "manually examine the application's behavior and attempt to identify any unusual input\nvalidation or "
          "other obstacles that may be in place.")
REQUEST = "GET /search/3?term=x HTTP/2\nHost: shop.test\n" + "".join(
    f"X-Header-{n}: {'v' * 60}\n" for n in range(12)) + "Connection: close"
RESPONSE = "HTTP/2 200 OK\nContent-Type: text/html\n\n" + "".join(
    f"<div class=\"row-{n}\">{'content ' * 8}</div>\n" for n in range(20)) + "END-OF-RESPONSE-1"

BURP_PDF = f"""Burp Scanner Report
1. Cross-site scripting (reflected)
Previous Next
There are 2 instances of this issue:
/search/2 [term parameter]
/search/3 [term parameter]
Issue background
Reflected cross-site scripting arises when data is copied into a response unsafely.
Issue remediation
Encode user input at every point where it is copied into a response.
Vulnerability classifications
CWE-79: Improper Neutralization of Input During Web Page Generation
1.1. https://shop.test/search/2 [term parameter]
Next
Summary
Severity: High
Confidence: Firm
Host: https://shop.test
Path: /search/2
Issue detail
{DETAIL}
Request 1
Response 1
1.2. https://shop.test/search/3 [term parameter]
Previous
Summary
Severity: High
Confidence: Certain
Host: https://shop.test
Path: /search/3
Issue detail
The payload x was echoed unmodified.
Request 1
{REQUEST}
Response 1
{RESPONSE}
Request 2
{REQUEST.replace("term=x", "term=y")}
Response 2
{RESPONSE.replace("END-OF-RESPONSE-1", "END-OF-RESPONSE-2")}
Report generated by Burp Suite web vulnerability scanner v2022.9.2, at Thu Oct 13 18:27:11 BST 2022.
HTTP/2 200 OK
Leftover: an exchange printed for another issue
"""


def _burp_pdf():
    act, info = BurpParser()._parse_plaintext(BURP_PDF)
    return {f.target.split(" ")[0]: f for f in act + info}


# -- the parsers --------------------------------------------------------------

def test_an_issue_detail_is_the_proof_whole_when_the_exchange_is_not_in_the_text():
    ev = _burp_pdf()["https://shop.test/search/2"].evidence
    assert ev == "[Issue detail]\n" + DETAIL
    assert ev.endswith("other obstacles that may be in place.")


def test_every_request_and_response_is_kept_whole():
    ev = _burp_pdf()["https://shop.test/search/3"].evidence
    assert [m for m in re.findall(r"\[HTTP [^\]]+\]", ev)] == [
        "[HTTP Request 1]", "[HTTP Response 1]", "[HTTP Request 2]", "[HTTP Response 2]"]
    assert REQUEST in ev and RESPONSE in ev
    assert ev.rstrip().endswith("END-OF-RESPONSE-2")


def test_the_last_response_stops_at_the_reports_closing_line():
    ev = _burp_pdf()["https://shop.test/search/3"].evidence
    assert "Report generated by Burp Suite" not in ev and "Leftover" not in ev


def test_a_burp_xml_exchange_is_kept_whole():
    xml = ("<?xml version='1.0'?><issues><issue><name>SQL injection</name><host>https://shop.test</host>"
           "<path>/filter</path><severity>High</severity><confidence>Firm</confidence>"
           "<issueDetail>The category parameter is injectable.</issueDetail><requestresponse>"
           f"<request base64=\"false\"><![CDATA[{REQUEST}]]></request>"
           f"<response base64=\"true\">{base64.b64encode(RESPONSE.encode()).decode()}</response>"
           "</requestresponse></issue></issues>")
    act, _info = BurpParser()._parse_xml(xml)
    ev = act[0].evidence
    assert ev.startswith("[HTTP Request]\n") and REQUEST in ev
    assert "[HTTP Response]\n" + RESPONSE in ev


def test_a_burp_html_exchange_is_kept_whole():
    html = ("<html><body><span class=\"BODH0\" id=\"1\">1.&nbsp;SQL injection</span>"
            "<h2>Summary</h2><table class=\"summary_table\"><tbody>"
            "<tr><td>Severity:&nbsp;&nbsp;</td><td><b>High</b></td></tr>"
            "<tr><td>Confidence:&nbsp;&nbsp;</td><td><b>Firm</b></td></tr>"
            "<tr><td>Host:&nbsp;&nbsp;</td><td><b>https://shop.test</b></td></tr>"
            "<tr><td>Path:&nbsp;&nbsp;</td><td><b>/filter</b></td></tr></tbody></table>"
            "<h2>Issue detail</h2><span class=\"TEXT\">The category parameter is injectable.</span>"
            # Burp escapes the exchange in its HTML report.
            f"<h2>Request 1</h2><div class=\"rr_div\">{escape(REQUEST)}</div>"
            f"<h2>Response 1</h2><div class=\"rr_div\">{escape(RESPONSE)}</div>"
            f"<h2>Request 2</h2><div class=\"rr_div\">{escape(REQUEST)}</div>"
            f"<h2>Response 2</h2><div class=\"rr_div\">{escape(RESPONSE.replace('-1', '-2'))}</div>"
            "</body></html>")
    act, info = BurpParser()._parse_html(html)
    ev = (act + info)[0].evidence
    assert ev.count("[Response ") == 2 and RESPONSE in ev
    assert ev.rstrip().endswith("END-OF-RESPONSE-2")


LONG_OUTPUT = "\n".join(f"  Certificate chain entry {n}: CN=host-{n}.example.test, O=Example" for n in range(60)) \
    + "\n  END-OF-PLUGIN-OUTPUT"

NESSUS = f"""<?xml version="1.0" ?>
<NessusClientData_v2><Report name="r"><ReportHost name="10.0.0.5">
<HostProperties><tag name="host-ip">10.0.0.5</tag></HostProperties>
<ReportItem port="443" svc_name="www" protocol="tcp" severity="2" pluginID="51192"
 pluginName="SSL Certificate Cannot Be Trusted" pluginFamily="General">
<description>The server's X.509 certificate cannot be trusted.</description>
<solution>Purchase or generate a proper SSL certificate for this service.</solution>
<risk_factor>Medium</risk_factor>
<plugin_output>{LONG_OUTPUT}</plugin_output>
</ReportItem></ReportHost></Report></NessusClientData_v2>
"""


def test_a_nessus_plugin_output_is_kept_whole():
    act, _info = parse_tool_file("scan.nessus", NESSUS, framework="VAPT")
    assert act[0].evidence == LONG_OUTPUT.strip()


def test_only_a_page_sized_body_is_cut_and_it_says_so():
    assert full_poc("x" * 50) == "x" * 50
    big = "\n".join("line %05d %s" % (n, "y" * 40) for n in range(1000))
    out = full_poc(big)
    assert len(out) < POC_MAX_CHARS + 100
    left = int(re.search(r"\[\.\.\. (\d+) more characters in the source file\]$", out).group(1))
    kept = out[:out.rindex("\n[...")]
    assert big.startswith(kept) and len(kept) + left == len(big)
    assert kept.endswith("y" * 40)                        # cut at a line, not mid-line


# -- the worker ---------------------------------------------------------------

def test_the_worker_stores_the_whole_output(tmp_path, monkeypatch):
    eng = create_engine("sqlite:///" + str(tmp_path / "vapt.db"))
    Base.metadata.create_all(eng)
    S = sessionmaker(bind=eng)
    monkeypatch.setattr(worker, "SessionLocal", S)
    s = S()
    s.add(AuditReport(session_id="p1", session_title="p1", framework="VAPT"))
    s.commit()
    s.close()
    worker._run_fast_technical_vapt_bg("p1", [{"name": "scan.nessus", "bytes": NESSUS.encode(), "text": None}],
                                       selected_sls=[], framework="VAPT")
    s = S()
    try:
        rep = s.query(AuditReport).filter(AuditReport.session_id == "p1").first()
        snip = s.query(Finding).filter(Finding.report_id == rep.id).first().evidence_snippet
    finally:
        s.close()
    assert snip.endswith("Plugin Output:\n" + LONG_OUTPUT.strip())


# -- the reports --------------------------------------------------------------

POC = ("Target Host: https://shop.test/search/3\nScanner:     Burp Suite\nPlugin Output:\n"
       f"[HTTP Request 1]\n{REQUEST}\n\n[HTTP Response 1]\n{RESPONSE}\n\n"
       f"[HTTP Request 2]\n{REQUEST}\n\n[HTTP Response 2]\n{RESPONSE.replace('-1', '-2')}")


def test_the_proof_splits_into_its_labelled_parts():
    from src.core.report_exporter import _poc_sections
    parts = _poc_sections(POC)
    assert [p[0] for p in parts] == ["", "HTTP Request 1", "HTTP Response 1", "HTTP Request 2", "HTTP Response 2"]
    assert parts[0][1] == "Target Host: https://shop.test/search/3\nScanner:     Burp Suite"
    assert parts[2][1] == RESPONSE
    assert _poc_sections("plain nmap output\n|   TLSv1.0:") == [("", "plain nmap output\n|   TLSv1.0:")]


def _finding():
    return {"control_id": "VAPT-1", "title": "Cross-site scripting (reflected)", "severity": "HIGH",
            "status": "Non-Compliant", "final_result": "NON_COMPLIANT", "target": "https://shop.test/search/3",
            "description": "Reflected XSS.", "recommendation": "Encode output.", "evidence_snippet": POC}


def test_the_vapt_pdf_prints_the_whole_proof_under_its_labels():
    from pypdf import PdfReader
    from src.core.report_exporter import export_pdf_report
    out = export_pdf_report("poc check", [_finding()], [], "FINAL", audit_type="vapt")
    text = "\n".join((p.extract_text() or "") for p in PdfReader(io.BytesIO(out)).pages)
    for label in ("HTTP Request 1", "HTTP Response 1", "HTTP Request 2", "HTTP Response 2"):
        assert label in text
    assert "END-OF-RESPONSE-1" in text and "END-OF-RESPONSE-2" in text
    assert "[HTTP Request 1]" not in text                 # a heading now, not a bracketed line


def test_the_vapt_docx_prints_the_whole_proof_under_its_labels():
    from docx import Document
    from src.core.report_exporter import export_docx_report
    out = export_docx_report("poc check", [_finding()], [], "FINAL", audit_type="vapt")
    d = Document(io.BytesIO(out))
    cell = next(c for t in d.tables for r in t.rows for c in r.cells if "END-OF-RESPONSE-2" in c.text)
    labels = [p.text for p in cell.paragraphs if p.runs and p.runs[0].bold]
    assert labels == ["HTTP Request 1", "HTTP Response 1", "HTTP Request 2", "HTTP Response 2"]
    assert RESPONSE in cell.text


# -- the page -----------------------------------------------------------------

def _function(src, name):
    start = src.index(f"function {name}(")
    depth, i = 0, src.index("{", start)
    while True:
        ch = src[i]
        depth += ch == "{"
        depth -= ch == "}"
        i += 1
        if depth == 0:
            return src[start:i]


def _run(expr):
    node = shutil.which("node")
    if not node:
        pytest.skip("node not available")
    src = io.open(APP_JS, encoding="utf-8").read()
    const = src[src.index("const _POC_LABEL_RE"):]
    const = const[:const.index("\n") + 1]
    script = "\n".join([
        "function escapeHtml(s) { return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'); }",
        const, _function(src, "pocSections"), _function(src, "pocHtml")])
    script += "\nprocess.stdout.write(JSON.stringify(%s));\n" % expr
    out = subprocess.run([node, "-e", script], capture_output=True, text=True, timeout=30)
    assert out.returncode == 0, out.stderr
    return json.loads(out.stdout)


def test_the_card_splits_the_proof_as_the_reports_do():
    got = _run("pocSections(%s)" % json.dumps(POC))
    assert [p["label"] for p in got] == ["", "HTTP Request 1", "HTTP Response 1", "HTTP Request 2", "HTTP Response 2"]
    assert got[2]["body"] == RESPONSE


def test_the_card_shows_each_part_whole_under_its_label():
    html = _run("pocHtml(%s)" % json.dumps(POC.split("Plugin Output:\n")[1]))
    assert html.count("<details open") == 4 and "max-height" not in html
    assert "END-OF-RESPONSE-2" in html


def test_a_vapt_card_uses_it_and_pqc_keeps_its_box():
    src = io.open(APP_JS, encoding="utf-8").read()
    assert "${isVaptOnlySession() ? pocHtml(_cleanPoc) : `<pre" in src


def test_a_pentest_reports_facts_become_chips():
    poc = "Source: pentest_report.pdf\nReported severity: LOW (CVSS 2.0)\nStatus in report: Closed / remediated\n\n| row |"
    html = _run("pocHtml(%s)" % json.dumps(poc))
    assert "<b>Source:</b> pentest_report.pdf" in html and "<b>Status in report:</b> Closed / remediated" in html
    assert html.count("<pre") == 1 and "| row |" in html
